---
name: Checks

on: [push]

jobs:                                       #jobs to perform by github
  test-lint:
    name: Test and Lint                     #just a user friendly name
    runs-on: ubuntu-20.04                   #used this runner bec docker-compose is pre-installed
    steps:
      - name: Loggin to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout                      #to make sure code is available to run the next step
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"

